name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'meeting-game-backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: meeting-game-backend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./meeting-game-backend
      run: npm ci
      
    - name: Run tests (if any)
      working-directory: ./meeting-game-backend
      run: npm test --if-present
      
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE }}
      run: |
        # Install Railway CLI
        npm install -g @railway/cli
        
        # Deploy to Railway
        railway login --token $RAILWAY_TOKEN
        railway service $RAILWAY_SERVICE
        railway up --service $RAILWAY_SERVICE 