name: Deploy Full Stack App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    name: Deploy Backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: meeting-game-backend/package-lock.json
        
    - name: Install backend dependencies
      working-directory: ./meeting-game-backend
      run: npm ci
      
    - name: Deploy Backend to Render
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        echo "Deploying backend to Render..."
        # This will trigger Render deployment
        # Make sure you have the Render service set up

  deploy-frontend:
    runs-on: ubuntu-latest
    name: Deploy Frontend
    needs: deploy-backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: meeting-game/package-lock.json
        
    - name: Install frontend dependencies
      working-directory: ./meeting-game
      run: npm ci
      
    - name: Build frontend
      working-directory: ./meeting-game
      env:
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      run: npm run build
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./meeting-game 